### ISSUE TITLE
Error for certain BBOB functions and dimension combination

### ISSUE THREAD

**Issue by MarcusCramer91** [jakobbossek/cmaesr#13]
For the simple example of 
fun = makeBBOBFunction(dimension = 10, fid = 1, iid = 1)
cmaes(objective.fun = fun)

an error is returned 
Error in if (fitn.ordered[1L] < best.fitness) { : 
  missing value where TRUE/FALSE needed

No additional stopping criteria were used (just the default setting).
For other functions, errors might appear for less than 10 dimensions also. The above code might take several runs for an error to appear due to non-determinism.

**Comment by MarcusCramer91** [comment]
Okay after some testing, I realized that the algorithm never checks against the upper and lower bounds? Adding this check removes the error. The algorithm quickly converges to the global optimum, however, still takes about 1000 iterations afterwards. This might potentially another bug? Or too weak convergence stopping criteria?

**Comment by jakobbossek** [comment]
That was not the reason. I made use of the `norm` function, which did not do what I actually wanted.
Fixed this. Thanks for reporting this!

Bounds handling is another `work in progress` (see #5) and despite your simple bound correction working for you, this is not the best approach to tackle this issue since the CMA-ES makes some important assumptions on the distribution of the search points. This is not longer guaranteed if a simple *force to bounds* approach is applied.
